#' [hs_mm_visium_comparison_AbBa.R]
#'
#' Comparison of regions of aberrant basaloid cells in both IPF and BLM Visium data 
#'
#' L. Franzén [lovisa.franzen@scilifelab.se]

#### Set up ####
##### Define params. ####
# SPECIES <- "mouse"
# SPECIES <- "human"
SPECIES <- "translational"
DIR_ROOT <- getwd()
DIR_DATA <- file.path(DIR_ROOT, "data")
DIR_RES <- file.path(DIR_ROOT, "results", "translational")
DIR_FIG <- file.path(DIR_RES, "figures")
DIR_FIG_OUT <- file.path(DIR_FIG, "AbBa")
DIR_OBJ_OUT <- file.path(DIR_RES, "objects", "AbBa")
dir.create(DIR_FIG_OUT); dir.create(DIR_OBJ_OUT)


##### Load libs ####
library(tidyverse)
library(dplyr)
library(STutility)
library(patchwork)
library(readxl)
library(writexl)
library(pheatmap)
library(harmony)
library(ggVennDiagram)

##### Other ####
source(file.path(DIR_ROOT, "scripts", "custom_functions.R"))
source(file.path(DIR_ROOT, "scripts", "custom_colors.R"))
theme_custom <- theme(axis.title.x = element_blank())
fig_res <- 500


#### Gene conversion data ####
gene_conv_df <- read.csv(file.path(DIR_DATA, "misc", "orthogene_conv_combined_hs_mm.csv"), row.names = 1)
rownames(gene_conv_df) <- gene_conv_df$symbol_hs_mm
gene_conv <- setNames(gene_conv_df$symbol_hs_mm, nm = gene_conv_df$symbol_hs)
gene_conv_mm <- setNames(gene_conv_df$symbol_hs_mm, nm = gene_conv_df$symbol_mm)

gene_conv_df$symbol_hs_mm2 <- gsub("_", "-", gene_conv_df$symbol_hs_mm)


#### Read gene annotation data ####
mm_cell_anno <- read.csv(file.path(DIR_ROOT, "data", "misc", "strunz_cell_type_groups.csv"), sep = ";")
hs_cell_anno <- read.csv(file.path(DIR_ROOT, "data", "misc", "habermann_cell_type_groups.csv"), sep = ";")

rownames(hs_cell_anno) <- hs_cell_anno$cell_name
rownames(mm_cell_anno) <- ifelse(!is.na(mm_cell_anno$cell_name), mm_cell_anno$cell_name, "NA")


#### Read se obj ####
##### Human #####
se_hs <- readRDS(file.path(DIR_RES, "..", "human", "objects", "hs_visium_preproc_A_se_obj_nmf.rds"))

##### Mouse #####
se_mm <- readRDS(file = file.path(DIR_RES, "..", "mouse", "objects", "mm_visium_preproc_se_obj_subset_d21_nmf30_c2l.rds"))
animal_ids <- se_mm$animal %>% unique()

# Add F14 subcluster metadata
se_mm_f14high <- readRDS(file.path(DIR_RES, "..", "mouse", "objects", "NMF30_d21", "mm_visium_nmf30_d21_f14high_subset.rds"))
mdata_add <- setNames(paste0("F14hi_C", se_mm_f14high$f14_subclusters), nm=names(se_mm_f14high$f14_subclusters))
se_mm <- AddMetaData(se_mm, mdata_add, "f14_subclusters")
se_mm$f14_subclusters[is.na(se_mm$f14_subclusters)] <- "other"
rm(se_mm_f14high)



#### AbBa-factor DEG comparison #### 
#' Generated by script 'hs_mm_visium_comparison_DEA.R'
#' Performing DEA on F14-hi-C0 spots vs whole controls, per species
res_f14c0 <- read.csv(file.path(DIR_RES, "objects", "DEA", "hs_ms_visium_pseudobulk_dea_res_joined_Control_IPF_or_BLMd21_region_f14c0.csv"), row.names = 1)

genes_pos_sign <- res_f14c0 %>% filter(padj<0.01, log2FoldChange>0)

genes_pos_sign_mm <- genes_pos_sign %>% filter(species=="mouse")
genes_pos_sign_hs <- genes_pos_sign %>% filter(species=="human")

shared_markers <- intersect(genes_pos_sign_mm$gene, genes_pos_sign_hs$gene)

# Venn: IPF and BLM d21
d_venn <- list(
  IPF = genes_pos_sign_hs$gene,
  BLM = genes_pos_sign_mm$gene)

# Save data
venn_df_save <- data.frame(group = c(rep("IPF", length(d_venn$IPF)), rep("BLM", length(d_venn$BLM))),
                           gene = c(d_venn$IPF, d_venn$BLM))
venn_df_save$overlap <- ifelse(duplicated(venn_df_save$gene)|duplicated(venn_df_save$gene, fromLast=T),
                               "both", 
                               venn_df_save$group)
write.csv(venn_df_save,
          file.path(DIR_OBJ_OUT, "hs_mm_visium_pseudobulk_dea_Control_vs_IPF_or_BLMd21_f14c0_positive_DEGs_venn.csv"), row.names = T)

# Plot
# pdf(file.path(DIR_FIG_OUT, "hs_mm_visium_pseudobulk_dea_Control_vs_IPF_or_BLMd21_f14c0_positive_DEGs_venn.pdf"),
#     width = 1.5, height = 1.5)
# ggVennDiagram(d_venn, label_alpha = 0,
#               edge_lty = "solid",
#               label = "count") +
#   scale_color_manual(values = c("#B26694", "#215288")) +
#   scale_fill_distiller(palette = "Greys", direction = 1) +
#   theme(legend.position = "none")
# dev.off()


#### AbBa-factor vs c2l correlation (Fig 5a) #### 
# human
hs_factor_cell_cor_data_group <- readRDS(file.path(DIR_ROOT, "results/human/objects/cell2location_habermann", "hs_visium_A_nmf_1-30_factor_cell_cor_data_group.rds"))
for(n in names(hs_factor_cell_cor_data_group)){
  hs_factor_cell_cor_data_group[[n]]$factor <- rownames(hs_factor_cell_cor_data_group[[n]])
}
hs_factor_cell_ipf_cor <- bind_rows(hs_factor_cell_cor_data_group[paste0("IPF_", 1:4)], .id = "subject") %>% subset(factor == "factor_14")
rownames(hs_factor_cell_ipf_cor) <- paste0(hs_factor_cell_ipf_cor$subject, ".F14")
hs_factor_cell_ipf_cor <- hs_factor_cell_ipf_cor[,colnames(hs_factor_cell_ipf_cor) %in% hs_cell_anno$cell_name]


# mouse (d21)
mm_factor_cell_cor_data_group <- readRDS(file.path(DIR_ROOT, "results/mouse/objects/NMF30_d21", "mm_visium_nmf30_d21_factor_cell_cor_data_group.rds"))
mm_factor_cell_cor_data_group <- mm_factor_cell_cor_data_group$animal_id
animal_ids_d21 <- names(mm_factor_cell_cor_data_group)
  
for(n in names(mm_factor_cell_cor_data_group)){
  message(n)
  mm_factor_cell_cor_data_group[[n]]$factor <- rownames(mm_factor_cell_cor_data_group[[n]])
}
mm_f14_d21_blm_c2l_cor <- bind_rows(mm_factor_cell_cor_data_group[grep("_b", animal_ids_d21, value = T)], .id = "subject") %>% subset(factor == "d21.F14")
rownames(mm_f14_d21_blm_c2l_cor) <- paste0(mm_f14_d21_blm_c2l_cor$subject, ".F14")
mm_f14_d21_blm_c2l_cor <- mm_f14_d21_blm_c2l_cor[,colnames(mm_f14_d21_blm_c2l_cor) %in% mm_cell_anno$cell_name]

# mm_f14_d21_blm_c2l_cor <- mm_factor_cell_cor_data_group$d21_BLM["d21.F14", ]
# mm_f14_d21_blm_c2l_cor[,colnames(mm_f14_d21_blm_c2l_cor) %in% mm_cell_anno$cell_name]


# mouse (d7)
mm_d7_factor_cell_cor_data_group <- readRDS(file.path(DIR_ROOT, "results/mouse/objects/NMF30_d7", "mm_visium_nmf30_d7_factor_cell_cor_data_group.rds"))
mm_d7_factor_cell_cor_data_group <- mm_d7_factor_cell_cor_data_group$animal_id

for(n in names(mm_d7_factor_cell_cor_data_group)){
  message(n)
  mm_d7_factor_cell_cor_data_group[[n]]$factor <- rownames(mm_d7_factor_cell_cor_data_group[[n]])
}
mm_f16_d7_blm_c2l_cor <- bind_rows(mm_d7_factor_cell_cor_data_group[grep("_b", animal_ids, value = T)], .id = "subject") %>% subset(factor == "d7.F16")
rownames(mm_f16_d7_blm_c2l_cor) <- paste0(mm_f16_d7_blm_c2l_cor$subject, ".F16")
mm_f16_d7_blm_c2l_cor <- mm_f16_d7_blm_c2l_cor[,colnames(mm_f16_d7_blm_c2l_cor) %in% mm_cell_anno$cell_name]


# Plot heatmap: pheatmap
pal_length <- col_scale_div_custom2 %>% length()
ph_colors <- col_scale_div_custom2
abs_max_val <- c(hs_factor_cell_ipf_cor, mm_f16_d7_blm_c2l_cor) %>% unlist() %>% max() %>% round(digits = 1)
ph_breaks <- c(seq(-abs_max_val, 0, length.out=ceiling(pal_length/2) + 1),
               seq(abs_max_val/pal_length, abs_max_val, length.out=floor(pal_length/2)))
pheatmap::pheatmap(t(hs_factor_cell_ipf_cor),
                   cellwidth = 10, cellheight = 10,
                   treeheight_col = 6, treeheight_row = 6,
                   color = ph_colors,
                   breaks = ph_breaks)
pheatmap::pheatmap(t(mm_f16_d7_blm_c2l_cor),
                   cellwidth = 10, cellheight = 10,
                   cluster_cols = F,
                   treeheight_col = 6, treeheight_row = 6,
                   color = ph_colors,
                   breaks = ph_breaks)

# Plot heatmap: geom_tile
abs_max_val <- c(hs_factor_cell_ipf_cor, mm_f14_d21_blm_c2l_cor) %>% unlist() %>% max() %>% round(digits = 1)
n_cells <- 15

# human
hs_cell_order <- colSums(hs_factor_cell_ipf_cor) %>% sort(decreasing = T) %>% names()
hs_factor_cell_ipf_cor_long <- hs_factor_cell_ipf_cor
hs_factor_cell_ipf_cor_long$subject <- gsub("\\.F14", "", rownames(hs_factor_cell_ipf_cor_long))
hs_factor_cell_ipf_cor_long <- pivot_longer(hs_factor_cell_ipf_cor_long, cols = colnames(hs_factor_cell_ipf_cor), names_to = "cell", values_to = "cor")
# hs_factor_cell_ipf_cor_long$cell <- factor(hs_factor_cell_ipf_cor_long$cell, levels = rev(hs_cell_order))
hs_factor_cell_ipf_cor_long <- merge(x=hs_factor_cell_ipf_cor_long, y=hs_cell_anno[, c("cell_name", "cell_name_special")], by.x="cell", by.y="cell_name")
hs_factor_cell_ipf_cor_long$cell_name_special <- factor(hs_factor_cell_ipf_cor_long$cell_name_special, levels = rev(hs_cell_anno[hs_cell_order,"cell_name_special"]))
hs_factor_cell_ipf_cor_long_filt <- hs_factor_cell_ipf_cor_long %>% filter(cell_name_special %in% hs_cell_anno[hs_cell_order,"cell_name_special"][1:n_cells])

p_hs <- ggplot(hs_factor_cell_ipf_cor_long_filt, aes(x=subject, y=cell_name_special, fill=cor)) +
  geom_tile() +
  scale_fill_gradientn(colours = col_scale_div_custom2, limits = c(-abs_max_val, abs_max_val)) +
  theme_dotplot +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "plain"), 
        legend.position = "left"); p_hs

# mouse (d21)
mm_cell_order <- colSums(mm_f14_d21_blm_c2l_cor) %>% sort(decreasing = T) %>% names()
mm_f14_d21_blm_c2l_cor_long <- mm_f14_d21_blm_c2l_cor
mm_f14_d21_blm_c2l_cor_long$subject <- gsub("\\.F14", "", rownames(mm_f14_d21_blm_c2l_cor_long))
mm_f14_d21_blm_c2l_cor_long <- pivot_longer(mm_f14_d21_blm_c2l_cor_long, cols = colnames(mm_f14_d21_blm_c2l_cor), names_to = "cell", values_to = "cor")
# mm_f14_d21_blm_c2l_cor_long$cell <- factor(mm_f14_d21_blm_c2l_cor_long$cell, levels = rev(mm_cell_order))
mm_f14_d21_blm_c2l_cor_long <- merge(x=mm_f14_d21_blm_c2l_cor_long, y=mm_cell_anno[, c("cell_name", "cell_name_special")], by.x="cell", by.y="cell_name")
mm_f14_d21_blm_c2l_cor_long$cell_name_special <- factor(mm_f14_d21_blm_c2l_cor_long$cell_name_special, levels = rev(mm_cell_anno[mm_cell_order,"cell_name_special"]))
mm_f14_d21_blm_c2l_cor_long_filt <- mm_f14_d21_blm_c2l_cor_long %>% filter(cell_name_special %in% mm_cell_anno[mm_cell_order,"cell_name_special"][1:n_cells])

p_mm <- ggplot(mm_f14_d21_blm_c2l_cor_long_filt, aes(x=subject, y=cell_name_special, fill=cor)) +
  geom_tile() +
  scale_fill_gradientn(colours = col_scale_div_custom2, limits = c(-abs_max_val, abs_max_val)) +
  scale_y_discrete(position = "right") +
  theme_dotplot +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "plain")); p_mm
p_mm_d21 <- p_mm

# mouse (d7)
mm_cell_order <- colSums(mm_f16_d7_blm_c2l_cor) %>% sort(decreasing = T) %>% names()
mm_f16_d7_blm_c2l_cor_long <- mm_f16_d7_blm_c2l_cor
mm_f16_d7_blm_c2l_cor_long$subject <- gsub("\\.F16", "", rownames(mm_f16_d7_blm_c2l_cor_long))
mm_f16_d7_blm_c2l_cor_long <- tidyr::pivot_longer(mm_f16_d7_blm_c2l_cor_long, cols = colnames(mm_f16_d7_blm_c2l_cor), names_to = "cell", values_to = "cor")
# mm_f16_d7_blm_c2l_cor_long$cell <- factor(mm_f16_d7_blm_c2l_cor_long$cell, levels = rev(mm_cell_order))
mm_f16_d7_blm_c2l_cor_long <- merge(x=mm_f16_d7_blm_c2l_cor_long, y=mm_cell_anno[, c("cell_name", "cell_name_special")], by.x="cell", by.y="cell_name")
mm_f16_d7_blm_c2l_cor_long$cell_name_special <- factor(mm_f16_d7_blm_c2l_cor_long$cell_name_special, levels = rev(mm_cell_anno[mm_cell_order,"cell_name_special"]))
mm_f16_d7_blm_c2l_cor_long_filt <- mm_f16_d7_blm_c2l_cor_long %>% filter(cell_name_special %in% mm_cell_anno[mm_cell_order,"cell_name_special"][1:n_cells])

p_mm_d7 <- ggplot(mm_f16_d7_blm_c2l_cor_long_filt, aes(x=subject, y=cell_name_special, fill=cor)) +
  geom_tile() +
  scale_fill_gradientn(colours = col_scale_div_custom2, limits = c(-abs_max_val, abs_max_val)) +
  scale_y_discrete(position = "right") +
  theme_dotplot +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "plain")); p_mm_d7


# combine
pdf(file.path(DIR_FIG_OUT, "hs_ms_visium_abba_factor_c2l_cor.pdf"), 
    width = 8, height = 3.6)
(p_hs|p_mm)+plot_layout(widths = c(3,4))
dev.off()

pdf(file.path(DIR_FIG_OUT, "hs_ms_visium_abba_factor_c2l_cor_d7-F16.pdf"), 
    width = 8, height = 3.6)
(p_hs|p_mm_d7)+plot_layout(widths = c(3,4))
dev.off()

pdf(file.path(DIR_FIG_OUT, "hs_ms_visium_abba_factor_c2l_cor_bothNMFd21d7.pdf"), 
    width = 10, height = 5)
((p_hs&labs(title="hs-NMF-F14"))|(p_mm_d21&labs(title="mm-NMFd21-F14"))|(p_mm_d7&labs(title="mm-NMFd7-F16"))) + plot_layout(widths = c(3,4,4)) & theme(legend.position = "bottom")
dev.off()


#### Plot spatial F14 subclusters #### 
se_hs$f14_subclusters[is.na(se_hs$f14_subclusters)] <- "other"
se_hs$f14_subclusters[se_hs$f14_subclusters!="other"] <- paste0("F14hi_C", 
                                                                se_hs$f14_subclusters[se_hs$f14_subclusters!="other"])
f14hi_cluster_names_hs <- se_hs$f14_subclusters[se_hs$f14_subclusters != "other"] %>% unique() %>% sort()
f14hi_cluster_names_mm <- se_mm$f14_subclusters[se_mm$f14_subclusters != "other"] %>% unique() %>% sort()

cluster_cols <- setNames(
           c("#DB8712", "#49C1AD", "#8D71A6", "#5DA6C6", "#E391BA",
             "#DB8712", "#49C1AD", "#8D71A6",
             "grey95"), 
             nm = c(f14hi_cluster_names_hs, 
                    f14hi_cluster_names_mm,
                    "other"))
cluster_cols <- c(cluster_cols, setNames(c("grey85", "grey70"), nm=c("fibrotic", "dense fibrosis")))


# Subset se obj to those with histopath annotations
se_hs_subset <- SubsetSTData(se_hs, !is.na(se_hs$annotation) & condition == "IPF")
se_mm_subset <- SubsetSTData(se_mm, !is.na(se_mm$annotation) & condition == "bleomycin")


#' Spatial
se_hs_subset$f14_subclusters2 <- ifelse(se_hs_subset$f14_subclusters != "other", 
                                        as.character(se_hs_subset$f14_subclusters),
                                        ifelse(se_hs_subset$annotation %in% c("Suspect Fibrosis"), 
                                               "dense fibrosis",
                                               ifelse(se_hs_subset$annotation %in% c("Diseased"), 
                                                      "fibrotic",
                                                      "other"
                                                      )
                                               )
                                        )
se_hs_subset$f14_subclusters2 <- factor(se_hs_subset$f14_subclusters2, levels = c(f14hi_cluster_names_hs, "dense fibrosis", "fibrotic", "other"))

se_mm_subset$f14_subclusters2 <- ifelse(se_mm_subset$f14_subclusters != "other", 
                                        as.character(se_mm_subset$f14_subclusters),
                                        ifelse(se_mm_subset$annotation %in% "Suspect Fibrosis/Fibroplasia", 
                                               "fibrotic",
                                               "other"
                                        ))
se_mm_subset$f14_subclusters2 <- factor(se_mm_subset$f14_subclusters2, levels = c(f14hi_cluster_names_mm, "fibrotic", "other"))

se_hs_subset$f14_subclusters2 %>% unique()
se_mm_subset$f14_subclusters2 %>% unique()

p_spat_hs <- ST.FeaturePlot(se_hs_subset,
                         features = "f14_subclusters2", 
                         ncol=3, cols = cluster_cols, 
                         label.by = "sample_name", 
                         pt.border = F,
                         pt.size = 0.75, show.sb = F) + 
  guides(fill = guide_legend(override.aes = list(size=2))) &
  theme(legend.position = "bottom", aspect.ratio = 1);p_spat_hs

p_spat_mm <- ST.FeaturePlot(se_mm_subset,
                            features = "f14_subclusters2", 
                            ncol=3, cols = cluster_cols, 
                            label.by = "sample_name", 
                            pt.border = F,
                            pt.size = 1, show.sb = F) + 
  guides(fill = guide_legend(override.aes = list(size=2))) &
  theme(legend.position = "bottom", aspect.ratio = 1);p_spat_mm

# save plot
png(file.path(DIR_FIG_OUT, paste0("hs_mm_visium_abba_factor_subcluster_spatial_all.png")), width = 14*fig_res, height = 10*fig_res, res = fig_res)
p_spat_hs|p_spat_mm
dev.off()

pdf(file.path(DIR_FIG_OUT, paste0("hs_mm_visium_abba_factor_subcluster_spatial_all.pdf")), width = 14, height = 10)
p_spat_hs|p_spat_mm
dev.off()


#' Only F14hiC0, FF, fibrotic, other
se_hs_subset$f14hiC0_fibrosis <- ifelse(test = (as.character(se_hs_subset$f14_subclusters2) %in% c("F14hi_C1", "F14hi_C2", "F14hi_C3", "F14hi_C4")), 
                                        yes = as.character(se_hs_subset$annotation),
                                        no = as.character(se_hs_subset$f14_subclusters2)
                                        )
se_hs_subset$f14hiC0_fibrosis <- ifelse(se_hs_subset$f14hiC0_fibrosis == "dense fibrosis", "fibroblastic foci", se_hs_subset$f14hiC0_fibrosis)
se_hs_subset$f14hiC0_fibrosis <- ifelse(test = (se_hs_subset$f14hiC0_fibrosis %in% c("Large Airway", "Normal Alveolar and Other", "Inflammation", "Blood Vessel")), 
                                        yes = "other",
                                        no = ifelse(
                                          test = (se_hs_subset$f14hiC0_fibrosis %in% c("Diseased")), 
                                          yes = "fibrotic",
                                          no = ifelse(
                                            test = (se_hs_subset$f14hiC0_fibrosis %in% c("Suspect Fibrosis")), 
                                            yes = "fibroblastic foci",
                                            no = se_hs_subset$f14hiC0_fibrosis
                                          )
                                          )
                                        )
unique(se_hs_subset$f14hiC0_fibrosis)


se_mm_subset$f14hiC0_fibrosis <- ifelse(test = (as.character(se_mm_subset$f14_subclusters2) %in% c("F14hi_C1", "F14hi_C2", "F14hi_C3", "F14hi_C4")), 
                                        yes = as.character(se_mm_subset$annotation),
                                        no = as.character(se_mm_subset$f14_subclusters2)
                                        )
se_mm_subset$f14hiC0_fibrosis <- ifelse(test = (se_mm_subset$f14hiC0_fibrosis %in% c("Large Airway", "Normal Alveolar and Other", "Inflammation", "Blood Vessel")), 
                                        yes = "other",
                                        no = ifelse(
                                          test = (se_mm_subset$f14hiC0_fibrosis %in% c("Diseased", "Suspect Fibrosis/Fibroplasia")), 
                                          yes = "fibrotic",
                                          no = se_mm_subset$f14hiC0_fibrosis
                                        )
                                        )
unique(se_mm_subset$f14hiC0_fibrosis)

cluster_cols2 <- setNames(
  c(
    "#BF8CA9",
    # "#DB8712",
    "grey50","grey75", "grey95"), 
    nm = c("F14hi_C0",
           "fibroblastic foci",
           "fibrotic",
           "other"))

p_spat_hs <- ST.FeaturePlot(se_hs_subset,
                            features = "f14hiC0_fibrosis", 
                            ncol=3, cols = cluster_cols2, 
                            label.by = "sample_name", 
                            pt.border = F,
                            pt.size = 0.75, show.sb = F) + 
  guides(fill = guide_legend(override.aes = list(size=2))) &
  theme(legend.position = "bottom", aspect.ratio = 1);p_spat_hs

p_spat_mm <- ST.FeaturePlot(se_mm_subset,
                            features = "f14hiC0_fibrosis", 
                            ncol=3, cols = cluster_cols2, 
                            label.by = "sample_name", 
                            pt.border = F,
                            pt.size = 1, show.sb = F) + 
  guides(fill = guide_legend(override.aes = list(size=2))) &
  theme(legend.position = "bottom", aspect.ratio = 1);p_spat_mm

pdf(file.path(DIR_FIG_OUT, paste0("hs_mm_visium_abba_factor_F14hiC0_fibrosis_spatial_all.pdf")), width = 14, height = 10)
p_spat_hs|p_spat_mm
dev.off()


#### Plot H&E spatial F14hiC0  #### 
se_hs_he <- SubsetSTData(se_hs_subset, expression = sample_name %in% c("IPF_3.TD031.B1.2", "IPF_4.TD042.B3.1"))
se_mm_he <- SubsetSTData(se_mm_subset, expression = sample_name %in% c("d21_bleo_4a", "d21_bleo_5b"))

se_hs_he <- LoadImages(se_hs_he, xdim = 2e3)
se_mm_he <- LoadImages(se_mm_he, xdim = 2e3)

# human
crop_window_list <- list("600x600+200+100", "600x600+400+700")
ImagePlot(se_hs_he)

se_hs_he_crop <- CropImages(se_hs_he, crop.geometry.list = list("1" = crop_window_list[[1]],
                                                                "2" = crop_window_list[[2]]))
he_crop_hs <- FeatureOverlay(se_hs_he_crop, 
                   features = "f14hiC0_fibrosis",
                   sampleids = c(2,1), ncols = 2,
                   label.by = "sample_name",
                   cols = "grey10", show.sb = T, 
                   pt.size = 2,
                   spots = subset(se_hs_he@meta.data, f14hiC0_fibrosis=="F14hi_C0") %>% rownames()) &
  theme(aspect.ratio = 1, legend.position = "bottom")

# mouse
crop_window_list <- list("400x400+700+150", "400x400+1050+750")
ImagePlot(se_mm_he)

se_mm_he_crop <- CropImages(se_mm_he, crop.geometry.list = list("1" = crop_window_list[[1]],
                                                                "2" = crop_window_list[[2]]))
he_crop_mm <- FeatureOverlay(se_mm_he_crop, 
                             features = "f14hiC0_fibrosis",
                             sampleids = c(1,2), ncols = 2,
                             label.by = "sample_name",
                             cols = "grey10", show.sb = T, 
                             pt.size = 3,
                             spots = subset(se_mm_he@meta.data, f14hiC0_fibrosis=="F14hi_C0") %>% rownames()) &
  theme(aspect.ratio = 1, legend.position = "bottom");he_crop_mm


# Save plots
pdf(file.path(DIR_FIG_OUT, paste0("hs_mm_visium_abba_factor_F14hiC0_fibrosis_spatial_HE_selected.pdf")), width = 5, height = 3)
ImagePlot(se_hs_he)
he_crop_hs
ImagePlot(se_mm_he)
he_crop_mm
dev.off()

# Plot Myofib values on crops
c2l_all <- read.csv(file.path(DIR_ROOT, "data", "human", "sc_deconvolution_habermann", "compiled_all_samples_cell_abundances.csv"), row.names = 1)
cell_type_col_names <- colnames(c2l_all)
cell_type_names <- gsub("c2l_", "", gsub("[.]$", "", gsub("..", "_", cell_type_col_names, fixed = TRUE)))
se_hs_he_crop <- AddMetaData(se_hs_he_crop, c2l_all)


pdf(file.path(DIR_FIG_OUT, paste0("hs_mm_visium_abba_factor_myofibroblast_spatial_HE_selected.pdf")), width = 5, height = 3)
print(FeatureOverlay(se_hs_he_crop, 
               features = "c2l_Myofibroblasts", 
               max.cutoff = 2,
               sampleids = c(2,1), 
               ncols = 2,
               label.by = "sample_name",
               cols = col_scale_mako %>% rev(), add.alpha = T,
               show.sb = T, 
               pt.size = 2) &
  theme(aspect.ratio = 1, legend.position = "bottom"))
print(FeatureOverlay(se_mm_he_crop, 
               features = "c2l_Myofibroblasts", max.cutoff = 2,
               sampleids = c(1,2), 
               ncols = 2,
               label.by = "sample_name",
               cols = col_scale_mako %>% rev(), add.alpha = T,
               show.sb = T, 
               pt.size = 3) &
  theme(aspect.ratio = 1, legend.position = "bottom"))
dev.off()



#### Shared-space analysis #### 
#' https://satijalab.org/seurat/articles/integration_introduction.html
#' 
#' 
# subset key sample data based on F14hiC0 abundance
hs_sample_select <- c("IPF_3.TD031.B1.2",  "IPF_3.TD032A.B2.2", "IPF_3.TD032B.B3.2",
                      "IPF_4.TD041A.B1.1", "IPF_4.TD041B.B2.1", "IPF_4.TD042.B3.1")
se_hs_subset <- SubsetSTData(se_hs, sample_name %in% hs_sample_select)

mm_sample_select <- c('d21_bleo_1', 'd21_bleo_2', 'd21_bleo_3', 'd21_bleo_4a', 'd21_bleo_5b')
se_mm_subset <- SubsetSTData(se_mm, sample_name %in% mm_sample_select)

# Create shared gene space assay
# extract count data and rename genes
hs_counts <- se_hs_subset@assays$RNA@counts
hs_counts <- hs_counts[rownames(hs_counts) %in% gene_conv_df$symbol_hs, ]
rownames(hs_counts) <- gene_conv[rownames(hs_counts)]

mm_counts <- se_mm_subset@assays$RNA@counts
mm_counts <- mm_counts[rownames(mm_counts) %in% gene_conv_df$symbol_mm, ]
rownames(mm_counts) <- gene_conv_mm[rownames(mm_counts)]

# filter on shared genes
shared_genes <- intersect(rownames(hs_counts), rownames(mm_counts))
hs_counts_filt <- hs_counts[shared_genes, ]
mm_counts_filt <- mm_counts[shared_genes, ]
dim(hs_counts_filt); dim(mm_counts_filt)

# add as new assay
se_hs_subset[['CountsShared']] <- CreateAssayObject(hs_counts_filt)
se_mm_subset[['CountsShared']] <- CreateAssayObject(mm_counts_filt)


##### Process new assays #####
###### All spots ######
####### Integrate data #######
# Normalize based on new data
se_hs_subset@assays$CountsShared[1:5,1:3]

se_hs_subset <- NormalizeData(se_hs_subset, assay = "CountsShared")
# se_hs_subset <- FindVariableFeatures(se_hs_subset, assay = "SCT")

se_mm_subset <- NormalizeData(se_mm_subset, assay = "CountsShared")
# se_mm_subset <- FindVariableFeatures(se_mm_subset, assay = "SCT")

# find integration fetures and achors
se_list <- list(se_hs_subset, se_mm_subset)
features <- SelectIntegrationFeatures(object.list = se_list, assay = c("CountsShared", "CountsShared"))
length(features);head(features)

anchors <- FindIntegrationAnchors(object.list = se_list, anchor.features = features, assay = c("CountsShared", "CountsShared"))

# Save Staffli obj
se_list_merged <- MergeSTData(se_list[[1]], se_list[[2]])
staffli_obj <- GetStaffli(se_list_merged)
saveRDS(staffli_obj, file.path(DIR_OBJ_OUT, "..", "joint_analysis_hs_mm_subset_se_staffli_obj.rds"))


# export
saveRDS(se_list, file.path(DIR_OBJ_OUT, "..", "joint_analysis_hs_mm_subset_se_obj.rds"))
saveRDS(anchors, file.path(DIR_OBJ_OUT, "..", "joint_analysis_hs_mm_subset_anchors.rds"))

# combine objects
se_comb <- IntegrateData(anchorset = anchors)
DefaultAssay(se_comb) <- "integrated"

# Add staffli
se_comb@tools$Staffli <- staffli_obj # readRDS(file.path(DIR_OBJ_OUT, "..", "joint_analysis_hs_mm_subset_se_staffli_obj.rds"))

# Process data
DefaultAssay(se_comb) <- "integrated"
se_comb <- ScaleData(se_comb, verbose = FALSE)

# VlnPlot(se_comb, features = c("nCount_RNA", "nFeature_RNA"), group.by = "sample_name", split.by = "species", pt.size = 0)
# VlnPlot(se_comb, features = c("COL1A1-Col1a1"), group.by = "sample_name", split.by = "species", pt.size = 0)
# ST.FeaturePlot(se_comb, features = c("nCount_RNA"), ncol = 6)


# export
saveRDS(se_comb, file.path(DIR_OBJ_OUT, "..", "joint_analysis_hs_mm_subset_se_obj_integrated.rds"))

# clear up objects
# rm(se_list);rm(anchors);rm(hs_counts);rm(mm_counts);rm(test)


###### Analyse data ######
#' read and pre-process object
se_comb <- readRDS(file.path(DIR_OBJ_OUT, "..", "joint_analysis_hs_mm_subset_se_obj_integrated.rds"))

se_comb$subject <- ifelse(!is.na(se_comb$subject_alias),
                          se_comb$subject_alias,
                          se_comb$animal
                          )

se_comb$barcode_original <- gsub("_[1-2]$", "", rownames(se_comb[[]]))

mm_mdat <- read.csv(file.path(DIR_RES, "../mouse", "objects", "NMF30_d21", "mm_visium_nmf30_d21_se_processed_metadata.csv"), row.names = 1)
rownames(mm_mdat) <- paste0(mm_mdat$barcode, "_2")

mm_mdat_add <- mm_mdat[, c("barcode", "f14_subclusters2", "d_cF14hi_C0", "f14_nbs_clusters")]
se_comb <- AddMetaData(se_comb, mm_mdat_add)

se_comb$d_cF14hi_C0[is.na(se_comb$d_cF14hi_C0)] <- 10
se_comb$d_c0[is.na(se_comb$d_c0)] <- 10

# ST.FeaturePlot(se_comb, features = "d_cF14hi_C0", ncol = 6, cols = col_scale_earth)
# ST.FeaturePlot(se_comb, features = "d_c0", ncol = 6, cols = col_scale_earth)


###### Plot shared DEGs ######
# Identify DEGS
res_f14c0 <- read.csv(file.path(DIR_RES, "objects", "DEA", "hs_ms_visium_pseudobulk_dea_res_joined_Control_IPF_or_BLMd21_region_f14c0.csv"), row.names = 1)

# F14-C0
genes_pos_sign <- res_f14c0 %>% filter(padj<0.01, log2FoldChange>0)
genes_pos_sign_mm <- genes_pos_sign %>% filter(species=="mouse")
genes_pos_sign_hs <- genes_pos_sign %>% filter(species=="human")
shared_markers <- intersect(genes_pos_sign_mm$gene, genes_pos_sign_hs$gene)

top_markers <- bind_rows(list(
  IPF = genes_pos_sign %>% filter(species=="human") %>% slice_max(order_by = log2FoldChange, n = 20),
  BLM = genes_pos_sign %>% filter(species=="mouse") %>% slice_max(order_by = log2FoldChange, n = 20),
  shared_ipf = genes_pos_sign_hs[shared_markers,] %>% slice_max(order_by = log2FoldChange, n = 10),
  shared_blm = genes_pos_sign_mm[shared_markers,] %>% slice_max(order_by = log2FoldChange, n = 10)))
top_markers$gene %>% unique()

genes_plot <- top_markers$gene %>% unique()
genes_plot <- gsub("_", "-", genes_plot)

# Prepare se object for plotting
se_comb_plot <- SubsetSTData(se_comb, f14_subclusters %in% c("other","F14hi_C0"))
se_comb_plot$groups <- paste0(se_comb_plot$species, "_", se_comb_plot$f14_subclusters)

pdf(file.path(DIR_FIG_OUT, "hs_ms_visium_abba_factor_DEGs_dotplot_long.pdf"), 
    width = 4.5, height = 10)
DotPlot(se_comb_plot, features = genes_plot, scale = F,
        group.by = "groups", assay = "CountsShared", dot.scale = 10) +
  scale_color_gradientn(colours = c(col_scale_acton)) +
  coord_flip() &
  theme_dotplot +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "plain"), 
        legend.position = "right")
dev.off()


# Identify DEGs more unique for F14-C0 than just in fibrotic areas
res_fib <- read.csv(file.path(DIR_RES, "objects", "DEA", "hs_ms_visium_pseudobulk_dea_res_joined_Control_IPF_or_BLMd21_or_BLMd7_region_fib.csv"), row.names = 1)
res_fib <- res_fib %>% filter(design != "condition_bleomycin_vs_control.fib.d7")

fib_genes_pos_sign <- res_fib %>% filter(padj<0.01, log2FoldChange>0)

spec_genes_pos_sign <- genes_pos_sign %>% 
  filter(!gene %in% fib_genes_pos_sign$gene)
dim(spec_genes_pos_sign)

shared_markers <- intersect(spec_genes_pos_sign %>% filter(species=="mouse") %>% pull(gene), 
                            spec_genes_pos_sign %>% filter(species=="human") %>% pull(gene))

top_markers <- bind_rows(list(
  IPF = spec_genes_pos_sign %>% filter(species=="human") %>% slice_max(order_by = log2FoldChange, n = 20),
  BLM = spec_genes_pos_sign %>% filter(species=="mouse") %>% slice_max(order_by = log2FoldChange, n = 20),
  shared = spec_genes_pos_sign[shared_markers,] %>% slice_max(order_by = log2FoldChange, n = 10)))
top_markers$gene %>% unique()

genes_plot <- top_markers$gene %>% unique()
genes_plot <- gsub("_", "-", genes_plot)

DotPlot(se_comb_plot, features = genes_plot, scale = F,
        group.by = "groups", assay = "CountsShared", dot.scale = 10) +
  scale_color_gradientn(colours = c(col_scale_acton)) +
  coord_flip() &
  theme_dotplot +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(face = "plain"), 
        legend.position = "right")


###### Find AbBa marker genes ###### 
#' !Important
se_comb$abba_group <- ifelse(se_comb$f14_subclusters=="F14hi_C0", "F14hi_C0", "other")
se_comb$abba_group <- paste0(se_comb$species, "_", se_comb$abba_group)

se_comb <- SetIdent(se_comb, value = "abba_group")
abba_markers_hs <- FindMarkers(se_comb, ident.1 = "human_F14hi_C0", ident.2 = "human_other", assay = "integrated")
abba_markers_mm <- FindMarkers(se_comb, ident.1 = "mouse_F14hi_C0", ident.2 = "mouse_other", assay = "integrated")

abba_markers_hs <- abba_markers_hs %>% 
  rownames_to_column(var = "gene") %>% 
  mutate(species = "human")
abba_markers_mm <- abba_markers_mm %>% 
  rownames_to_column(var = "gene") %>% 
  mutate(species = "mouse")

abba_markers <- bind_rows(abba_markers_hs, abba_markers_mm)
abba_markers$gene_hs <- sapply(strsplit(abba_markers$gene, "-"), "[[", 1)
abba_markers$gene_mm <- sapply(strsplit(abba_markers$gene, "-"), "[[", 2)

#' Export results
write.csv(abba_markers,
          file.path(DIR_OBJ_OUT, "hs_mm_visium_abba_factor_FindMarkers_f14c0_vs_other_within_species_res.csv"), row.names = F)

# Process markers
abba_markers <- read.csv(file.path(DIR_OBJ_OUT, "hs_mm_visium_abba_factor_FindMarkers_f14c0_vs_other_within_species_res.csv"))
abba_markers$gene %>% unique() %>% length()

pval_cutoff <- 0.01 # 0.0001
abba_markers_sign <- abba_markers %>% filter(p_val_adj<pval_cutoff & avg_log2FC>0)
dim(abba_markers_sign)
abba_markers_sign$gene %>% unique() %>% length()

abba_markers_sign %>% arrange(desc(avg_log2FC)) %>% head(n=20)

shared_markers <- abba_markers_sign$gene[duplicated(abba_markers_sign$gene)]
shared_markers <- subset(abba_markers_sign, species=="human" & gene %in% shared_markers) %>% arrange(desc(avg_log2FC)) %>% pull(gene)
markers_hs <- subset(abba_markers_sign, species=="human" & !gene %in% shared_markers) %>% arrange(desc(avg_log2FC)) %>% pull(gene)
markers_mm <- subset(abba_markers_sign, species=="mouse" & !gene %in% shared_markers) %>% arrange(desc(avg_log2FC)) %>% pull(gene)
length(shared_markers);length(markers_hs);length(markers_mm)

# Heatmap
spots_keep <- subset(se_comb[[]], f14_subclusters == "F14hi_C0") %>% rownames()
se_comb_f14hiC0 <- SubsetSTData(se_comb, spots = spots_keep)

pdf(file.path(DIR_FIG_OUT, "hs_mm_visium_abba_factor_FindMarkers_f14c0_vs_other_within_species_padj001_heatmap.pdf"), 
    width = 6, height = 24)
# pdf(file.path(DIR_FIG_OUT, "hs_mm_visium_abba_factor_FindMarkers_f14c0_vs_other_within_species_padj00001_heatmap.pdf"), 
#     width = 6, height = 24)
mapal <- colorRampPalette(rev(col_scale_div_expr))(256)
DoHeatmap(se_comb_f14hiC0, 
          assay = "integrated",
          group.by = "abba_group", 
          disp.min = -2, disp.max = 2, 
          group.colors = c("#B26694", "#215288"),
          size = 8,
          features = c(markers_hs, shared_markers, markers_mm)) +
  scale_fill_gradientn(colours = rev(mapal)) +
  theme(axis.text = element_text(size=6))
dev.off()

#'-> IPA analysis

